package me.monster.lab.apkplugin;

public class TaskInfo {
    long total;      //task执行总时长

    String path;
    long start;      //task 执行开始时间
    long end;        //task 结束时间
    String taskName;

    String taskNames = "assemble\n" +
            "assembleAndroidTest\n" +
            "build\n" +
            "buildDependents\n" +
            "buildEnvironment\n" +
            "buildNeeded\n" +
            "check\n" +
            "checkFileLocation\n" +
            "clean\n" +
            "cleanBuildCache\n" +
            "compileLint\n" +
            "components\n" +
            "connectedCheck\n" +
            "consumeConfigAttr\n" +
            "dependencies\n" +
            "dependencyInsight\n" +
            "dependentComponents\n" +
            "deviceCheck\n" +
            "extractProguardFiles\n" +
            "help\n" +
            "lint\n" +
            "lintFix\n" +
            "model\n" +
            "preBuild\n" +
            "prepareKotlinBuildScriptModel\n" +
            "projects\n" +
            "properties\n" +
            "resolveConfigAttr\n" +
            "sourceSets\n" +
            "tasks\n" +
            "uninstallAll\n" +
            "null\n" +
            "prepareLintJar\n" +
            "prepareLintJarForPublish\n" +
            "createMockableJar\n" +
            "connectedAndroidTest\n" +
            "deviceAndroidTest\n" +
            "test\n" +
            "assembleDebug\n" +
            "bundleDebug\n" +
            "preDebugBuild\n" +
            "generateDebugSources\n" +
            "generateDebugResources\n" +
            "generateDebugAssets\n" +
            "compileDebugSources\n" +
            "checkDebugManifest\n" +
            "writeDebugModuleMetadata\n" +
            "writeDebugApplicationId\n" +
            "mainApkListPersistenceDebug\n" +
            "reportBuildArtifactsDebug\n" +
            "createDebugCompatibleScreenManifests\n" +
            "processDebugManifest\n" +
            "generateDebugResValues\n" +
            "compileDebugRenderscript\n" +
            "mergeDebugResources\n" +
            "mergeDebugShaders\n" +
            "compileDebugShaders\n" +
            "mergeDebugAssets\n" +
            "generateDebugBuildConfig\n" +
            "processDebugResources\n" +
            "bundleDebugResources\n" +
            "processDebugJavaRes\n" +
            "compileDebugAidl\n" +
            "mergeDebugJniLibFolders\n" +
            "mergeDebugNativeLibs\n" +
            "generateDebugFeatureMetadata\n" +
            "validateSigningDebug\n" +
            "signingConfigWriterDebug\n" +
            "javaPreCompileDebug\n" +
            "compileDebugJavaWithJavac\n" +
            "bundleDebugClasses\n" +
            "mergeDebugGeneratedProguardFiles\n" +
            "mergeDebugJavaResource\n" +
            "transformClassesWithDexBuilderForDebug\n" +
            "checkDebugDuplicateClasses\n" +
            "mergeExtDexDebug\n" +
            "mergeProjectDexDebug\n" +
            "mergeLibDexDebug\n" +
            "stripDebugDebugSymbols\n" +
            "packageDebug\n" +
            "installDebug\n" +
            "uninstallDebug\n" +
            "lintDebug\n" +
            "generateDebugFeatureTransitiveDeps\n" +
            "buildDebugPreBundle\n" +
            "collectDebugDependencies\n" +
            "packageDebugBundle\n" +
            "signDebugBundle\n" +
            "configureDebugDependencies\n" +
            "makeApkFromBundleForDebug\n" +
            "packageDebugUniversalApk\n" +
            "extractApksForDebug\n" +
            "assembleDebugUnitTest\n" +
            "preDebugUnitTestBuild\n" +
            "generateDebugUnitTestSources\n" +
            "generateDebugUnitTestResources\n" +
            "generateDebugUnitTestAssets\n" +
            "compileDebugUnitTestSources\n" +
            "processDebugUnitTestJavaRes\n" +
            "dummydebugUnitTest\n" +
            "javaPreCompileDebugUnitTest\n" +
            "compileDebugUnitTestJavaWithJavac\n" +
            "bundleDebugUnitTestClasses\n" +
            "testDebugUnitTest\n" +
            "assembleRelease\n" +
            "bundleRelease\n" +
            "preReleaseBuild\n" +
            "generateReleaseSources\n" +
            "generateReleaseResources\n" +
            "generateReleaseAssets\n" +
            "compileReleaseSources\n" +
            "checkReleaseManifest\n" +
            "writeReleaseModuleMetadata\n" +
            "writeReleaseApplicationId\n" +
            "mainApkListPersistenceRelease\n" +
            "reportBuildArtifactsRelease\n" +
            "createReleaseCompatibleScreenManifests\n" +
            "processReleaseManifest\n" +
            "generateReleaseResValues\n" +
            "compileReleaseRenderscript\n" +
            "mergeReleaseResources\n" +
            "mergeReleaseShaders\n" +
            "compileReleaseShaders\n" +
            "mergeReleaseAssets\n" +
            "generateReleaseBuildConfig\n" +
            "processReleaseResources\n" +
            "bundleReleaseResources\n" +
            "processReleaseJavaRes\n" +
            "compileReleaseAidl\n" +
            "mergeReleaseJniLibFolders\n" +
            "mergeReleaseNativeLibs\n" +
            "generateReleaseFeatureMetadata\n" +
            "signingConfigWriterRelease\n" +
            "javaPreCompileRelease\n" +
            "compileReleaseJavaWithJavac\n" +
            "bundleReleaseClasses\n" +
            "mergeReleaseGeneratedProguardFiles\n" +
            "mergeReleaseJavaResource\n" +
            "transformClassesWithDexBuilderForRelease\n" +
            "checkReleaseDuplicateClasses\n" +
            "mergeExtDexRelease\n" +
            "mergeDexRelease\n" +
            "stripReleaseDebugSymbols\n" +
            "packageRelease\n" +
            "uninstallRelease\n" +
            "lintVitalRelease\n" +
            "lintRelease\n" +
            "generateReleaseFeatureTransitiveDeps\n" +
            "buildReleasePreBundle\n" +
            "collectReleaseDependencies\n" +
            "packageReleaseBundle\n" +
            "signReleaseBundle\n" +
            "configureReleaseDependencies\n" +
            "makeApkFromBundleForRelease\n" +
            "packageReleaseUniversalApk\n" +
            "extractApksForRelease\n" +
            "assembleReleaseUnitTest\n" +
            "preReleaseUnitTestBuild\n" +
            "generateReleaseUnitTestSources\n" +
            "generateReleaseUnitTestResources\n" +
            "generateReleaseUnitTestAssets\n" +
            "compileReleaseUnitTestSources\n" +
            "processReleaseUnitTestJavaRes\n" +
            "dummyreleaseUnitTest\n" +
            "javaPreCompileReleaseUnitTest\n" +
            "compileReleaseUnitTestJavaWithJavac\n" +
            "bundleReleaseUnitTestClasses\n" +
            "testReleaseUnitTest\n" +
            "assembleDebugAndroidTest\n" +
            "preDebugAndroidTestBuild\n" +
            "generateDebugAndroidTestSources\n" +
            "generateDebugAndroidTestResources\n" +
            "generateDebugAndroidTestAssets\n" +
            "compileDebugAndroidTestSources\n" +
            "mainApkListPersistenceDebugAndroidTest\n" +
            "processDebugAndroidTestManifest\n" +
            "generateDebugAndroidTestResValues\n" +
            "compileDebugAndroidTestRenderscript\n" +
            "mergeDebugAndroidTestResources\n" +
            "mergeDebugAndroidTestShaders\n" +
            "compileDebugAndroidTestShaders\n" +
            "mergeDebugAndroidTestAssets\n" +
            "generateDebugAndroidTestBuildConfig\n" +
            "processDebugAndroidTestResources\n" +
            "bundleDebugAndroidTestResources\n" +
            "processDebugAndroidTestJavaRes\n" +
            "compileDebugAndroidTestAidl\n" +
            "mergeDebugAndroidTestJniLibFolders\n" +
            "mergeDebugAndroidTestNativeLibs\n" +
            "javaPreCompileDebugAndroidTest\n" +
            "compileDebugAndroidTestJavaWithJavac\n" +
            "bundleDebugAndroidTestClasses\n" +
            "mergeDebugAndroidTestGeneratedProguardFiles\n" +
            "mergeDebugAndroidTestJavaResource\n" +
            "transformClassesWithDexBuilderForDebugAndroidTest\n" +
            "checkDebugAndroidTestDuplicateClasses\n" +
            "mergeExtDexDebugAndroidTest\n" +
            "mergeProjectDexDebugAndroidTest\n" +
            "mergeLibDexDebugAndroidTest\n" +
            "validateSigningDebugAndroidTest\n" +
            "signingConfigWriterDebugAndroidTest\n" +
            "packageDebugAndroidTest\n" +
            "installDebugAndroidTest\n" +
            "uninstallDebugAndroidTest\n" +
            "connectedDebugAndroidTest\n" +
            "reportSourceSetTransformAndroidTest\n" +
            "reportSourceSetTransformAndroidTestDebug\n" +
            "reportSourceSetTransformDebug\n" +
            "reportSourceSetTransformMain\n" +
            "reportSourceSetTransformRelease\n" +
            "reportSourceSetTransformTest\n" +
            "reportSourceSetTransformTestDebug\n" +
            "reportSourceSetTransformTestRelease\n" +
            "androidDependencies\n" +
            "signingReport\n" +
            "compileDebugAndroidTestKotlin\n" +
            "compileDebugUnitTestKotlin\n" +
            "compileDebugKotlin\n" +
            "compileReleaseUnitTestKotlin\n" +
            "compileReleaseKotlin\n" +
            "bundle";
}